language: scala
sudo: false
scala:
   - 2.11.12
matrix:
  include:
  - scala: 2.12.8
    jdk: oraclejdk8
  - scala: 2.13.0-M5
    jdk: oraclejdk8

script:
- sbt ++$TRAVIS_SCALA_VERSION test proto26:test mimaReportBinaryIssues
